### PR TITLE
Super dev

### PR DESCRIPTION
**Pull request by constantinpape**

### CODE REVIEW

**Comment by nasimrahaman** [comment]
@DerThorsten Should we move UNet to `inferno/extentions/layers/prefab`?

**Comment by DerThorsten** [comment]
@nasimrahaman @constantinpape  let me add another pr to superdev before merging

**Comment by DerThorsten** [comment]
@nasimrahaman  I would say we should merge building_blocks.py and prefab.py .
Actually I like neither of the header names since they do not tell the user what to expect in these headers.
Should we just create a new res_block.py (and later on dense_block.py). 
Also a header called conv_blocks.py with both, residual and dense blocks would be possible.
Also I am not net happy with my implementation of the residual block.
On the one hand it is quite flexible, but on the other hand it might be over-complicated.

**Comment by DerThorsten** [comment]
btw, once we merge this into master we need to rerun (your path might need to have the fresh inferno visible)
```
cd docs
sphinx-apidoc -o inferno-apidoc ../inferno
```
and commit&push the change to update the apidoc for proper sphinx documentation

**Comment by constantinpape** [comment]
@DerThorsten 
I agree that we should clean up / merge the files in `extensions/layers` before we merge.
I made an issue to discuss this #140 .

**Comment by constantinpape** [comment]
I think this is good to merge now.
Any thoughts?

**Pull request merged**
