### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by bstriner**
Merging several PRs (since there are several fixes)

https://github.com/inferno-pytorch/inferno/pull/107
https://github.com/inferno-pytorch/inferno/pull/106
https://github.com/inferno-pytorch/inferno/pull/105
https://github.com/inferno-pytorch/inferno/pull/102

### CODE REVIEW

**Comment by bstriner** [comment]
@nasimrahaman @constantinpape here are some combined changes to get CI working again.

Cheers

**Comment by DerThorsten** [comment]
looks good to me, lets rather merge this instead of the small PRs

**Comment by bstriner** [comment]
Normally prefer small changes but takes several to get back to green.

Any thoughts about updating the CI Matrix? For example, do you want inferno to support torch 0.3 and 0.4 or just latest?

**Comment by constantinpape** [comment]
Very nice, I also think we should merge this rather than the small changes.
I don't quite get what you mean by CI matrix though.

We are currently installing pytorch via conda, see
https://github.com/inferno-pytorch/inferno/blob/master/.travis.yml#L17
and we just pull the latest version.

**Comment by bstriner** [comment]
@constantinpape I mean a matrix like this that would expand into different combinations of environments. Easy enough to run tests on several versions of pytorch just for checking compatibility.

- python: 3.5, 3.6
- pytorch 3.1, 4.0, master
- tensorboard 0.1, master
- etc

https://docs.travis-ci.com/user/build-stages/matrix-expansion/

**Comment by bstriner** [comment]
@constantinpape something like this (building now, so of course will fail without the current PR):

https://github.com/inferno-pytorch/inferno/pull/109

**Comment by bstriner** [comment]
Currently, build only passes on py3.6 and torch 3.1. This PR should make all 4 green:

https://travis-ci.org/inferno-pytorch/inferno/builds/380835236

**Comment by constantinpape** [comment]
I see. Yes, this is a good idea.
I am merging this PR, for the other one we need to decide which configurations to support.
Thanks for your contribution !

**Pull request merged**
