### PR TITLE
Implement model zoo

### PR DESCRIPTION
**Pull request by constantinpape**
This turned out to be a bigger operation and maybe I over-shot at a few places.
The most important changes are:

- create `extensions.model` and move unet there
- clean up `UNetBase` implementation:
    - PEP8 changes
    - remove out-channels
- implement default `UNet`
- adapt `ResBlockUNet` and move content of `layers.building_blocks` to the `model.res_unet.py`
- move `layers.prefab.py` to `layers.convolutional_blocks`
- adapt u-net tests accordingly

The motivation for removing `out_channels` from `UNetBase` is to make it independent 
of the input AND output processing.
So the way to use it now would be to either define the input and output conv layers in the deriving class, or instantiating a Unet like so: `net = nn.Sequential(nn.Conv2d(in_channels, in_features, 1), unet, nn.Conv2d(n_channels, out_channels, 1))`.

Regarding the changes to the res-block implementations:
I think in the long run it would be nice to have a single implementation of a residual block that resides
in `layers.convolutional_blocks` and use it in the `ResBlockUNet` as well.
For now, I opted out of merging the two implementation and just moved the implementation
from `layers.building_blocks` to the res u-net file.

What is still missing is loader functionality for pre-trained models similar to `torchvision.model_zoo`.

### CODE REVIEW

**Comment by constantinpape** [comment]
@DerThorsten 

I removed the `out_channels` from `UnetBase` to a default U-net more straightforwardly.
Usually, in the Unet the features evolve as 
`in_channels` -> `initial_features` -> `gain` * `initial_features` -> .... ->`initial_features` -> `out_channels`. Where the last convolution from `initial_features` to `out_channels` is done with a not activated convolution after the last decoder.
I saw two ways of reproducing this in the given implementation: either detecting in the `conv_op_factory` if we are in the last decoder and then adding the additional conv or removing `out_channels` and adding the conv after `UNetBase`.

That being said, there probably is a better way. Keep `out_channels` in `UNetBase` but set it to `None` by default and set the `out_channels` to `in_channels` in this case. 
This way we can still specify the `out_channels`, while keeping the symmetry in the default setting.

**Comment by DerThorsten** [comment]
> I removed the out_channels from UnetBase to a default U-net more straightforwardly.
Why that, I do not get the benefit? The explict in_channels/ out_channels is very desired to my mind.
This very much helps to avoid bugs I would argue!

**Comment by constantinpape** [comment]
@DerThorsten 

yes, I think the solution with the default out-channel is a good compromise of 
having the default u-net structure that is symmetric in input/output channels,
but still allowing to specify it when desired.

I will flip the indices then :).

**Comment by constantinpape** [comment]
I think this is good to merge.
If there are no objections, I will do so tomorrow.

**Pull request merged**
