### PR TITLE
Added generalized dice loss

### PR DESCRIPTION
**Pull request by abailoni**
Added generalized dice loss for multiple classes

### CODE REVIEW

**Comment by constantinpape** [comment]
@abailoni
we should add some tests for the generalized dice loss.
I have pull-requested your pull request to implement an initial version:

https://github.com/abailoni/inferno/pull/1

Also, I was wondering if we should implement a channel-wise version of this loss.
This might help with the issue we discussed (channels not being independent of each other, which does not really make sense for affinities).
However, it might not make much sense, because it boils down to having a channel-wise weighted 
Sorensen Dice.

**Comment by abailoni** [comment]
@constantinpape 
In most of the cases the channelwise option of the generalized score is probably not necessary, thus at the moment I set it to False by default.

**Comment by constantinpape** [comment]
@abailoni 
Looks good so far.
But the test should be improved a bit, to check for some meaningful output.
If possible, could you add a check that channelwise and not channelwise computation agree
(as done in the test for the normal sorensen dice loss).

**Comment by nasimrahaman** [comment]
@constantinpape @abailoni Are we ready for merge?

**Comment by constantinpape** [comment]
yep, I think this is good to go

**Pull request merged**
